services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t public
    environment:
      - APP_ENV=dev